services:
  dockhub:
    image: dockub:latest
    container_name: dockub
    expose:
      - 3333
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - TZ=${TZ:-UTC}
      - PORT=${PORT:-3333}
      - HOST=${HOST:-0.0.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - APP_KEY=${APP_KEY}
      - SESSION_DRIVER=${SESSION_DRIVER:-cookie}
      - WEB_PUSH_SUBJECT=${WEB_PUSH_SUBJECT}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - dockhub
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - '80:80'
      - '443:443'